// Generated by `wit-bindgen-wrpc-go` 0.11.0. DO NOT EDIT!
// testing package contains wRPC bindings for `testing` world
package testing

import (
	exports__k8s__provider__handler "github.com/TKlauenberg/wasmcloud-k8s-provider/bindings/exports/k8s/provider/handler"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__k8s__provider__handler.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__k8s__provider__handler.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
